# Chapter 2 快速浏览数据

## 2.1 绘制散点图
```{r}
plot(mtcars$wt, mtcars$mpg)

```
```{r}
library(ggplot2)

ggplot(mtcars, aes(x = wt, y = mpg)) + 
  geom_point()

```
```{r}
ggplot(data = NULL, aes(x = mtcars$wt, y = mtcars$mpg)) + 
  geom_point()

```

## 2.2 绘制折线图
```{r}
plot(pressure$temperature, pressure$pressure, type = "l")

```
```{r}
plot(pressure$temperature, pressure$pressure, type = "l") 
points(pressure$temperature, pressure$pressure)

lines(pressure$temperature, pressure$pressure/2, col = "red") 
points(pressure$temperature, pressure$pressure/2, col = "red")

```
```{r}
library(ggplot2)

ggplot(pressure, aes(x = temperature, y = pressure)) +
  geom_line()

```
```{r}
ggplot(pressure, aes(x = temperature, y = pressure)) + 
  geom_line() + 
  geom_point()

```

## 2.3 绘制条形图
```{r}
# 首先看一下 BOD 数据
BOD
#> Time demand
#> 1 1 8.3
#> 2 2 10.3
#> 3 3 19.0
#> 4 4 16.0
#> 5 5 15.6
#> 6 7 19.8

barplot(BOD$demand, names.arg = BOD$Time)

```
```{r}
# 值为 4 的频数为 11，值为 6 的频数为 7，而值为 8 的则有 14 个
table(mtcars$cyl)

```
```{r}
# 生成频数表
barplot(table(mtcars$cyl))

```
```{r}
library(ggplot2)

# 变量值的频数表。这里使用的是 BOD 数据框, 时间（time）列对应 x 值，需求（demand）列对应 y 值。
ggplot(BOD, aes(x = Time, y = demand)) +
  geom_col()

#  将 x 转化为因子型变量 , 令系统将其视作离散值
ggplot(BOD, aes(x = factor(Time), y = demand)) +
  geom_col()

```
```{r}
# 频数条形图。这里使用的是 mtcars 数据框， cyl 列对应 x ，而 y 值则通过统计 cyl 各取值对应行的数量来计算。
ggplot(mtcars, aes(x = cyl)) +
  geom_bar()

# 频数条形图。
ggplot(mtcars, aes(x = factor(cyl))) +
  geom_bar()

```

## 2.4 绘制直方图
```{r}
hist(mtcars$mpg)

# 通过 breaks 参数指定大致组距
hist(mtcars$mpg, breaks = 10)

```
```{r}
library(ggplot2)
ggplot(mtcars, aes(x = mpg)) + 
  geom_histogram()
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.

# 更宽的组距
ggplot(mtcars, aes(x = mpg)) +
  geom_histogram(binwidth = 4)

```

## 2.5 绘制箱型图
```{r}
plot(ToothGrowth$supp, ToothGrowth$len)

```
```{r}
# 公式语法
boxplot(len ~ supp, data = ToothGrowth)

# 在 x 轴上引入两变量的交互
boxplot(len ~ supp + dose, data = ToothGrowth)

```
```{r}
library(ggplot2)

ggplot(mtcars, aes(x = wt, y = mpg)) +
  geom_point()

```
```{r}
ggplot(ToothGrowth, aes(x = interaction(supp, dose), y = len)) +
  geom_boxplot()

```

## 2.6 绘制函数图像
```{r}
curve(x^3 - 5 * x, from = -4, to = 4)

```
```{r}
# 绘制用户自定义的函数图像
myfun <- function(xvar) {
  1/(1 + exp(-xvar + 10))
}
curve(myfun(x), from = 0, to = 20)
# 添加直线：
curve(1-myfun(x), add = TRUE, col = "red")

```
```{r}
library(ggplot2)
# 将 x 轴的取值范围设定为 0 到 20
ggplot(data.frame(x = c(0, 20)), aes(x = x)) +
  stat_function(fun = myfun, geom = "line")

```

