# Chapter 8 坐标轴

## 8.1 交换 x 轴和 y 轴
```{r}
library(ggplot2)
library(magrittr)

```
```{r}
ggplot(PlantGrowth, aes(x = group, y = weight)) +
  geom_boxplot() 
ggplot(PlantGrowth, aes(x = group, y = weight)) + 
  geom_boxplot() + 
  coord_flip()

```
```{r}
ggplot(PlantGrowth, aes(x=group, y=weight)) +
  geom_boxplot() +
  coord_flip() +
  scale_x_discrete(limits = rev(levels(PlantGrowth$group)))

```

## 8.2 设置连续型坐标轴的值域
```{r}
pg_plot <- ggplot(PlantGrowth, aes(x = group, y = weight)) + 
  geom_boxplot()

# 显示基本图形
pg_plot

pg_plot + 
  ylim(0, max(PlantGrowth$weight))

```
```{r}
ylim(0, 10)
scale_y_continuous(limits = c(0, 10))

```
```{r}
pg_plot +
  ylim(0, 10) +
  scale_y_continuous(breaks = c(0, 5, 10))

pg_plot +
  scale_y_continuous(breaks = c(0, 5, 10)) +
  ylim(0, 10)

```
```{r}
pg_plot + 
  scale_y_continuous(limits=c(0, 10), breaks=c(0, 5, 10))

```
```{r}
pg_plot + 
  scale_y_continuous(limits = c(5, 6.5))  # 与使用ylim()相同

pg_plot + 
  coord_cartesian(ylim = c(5, 6.5))

```
```{r}
pg_plot + 
  expand_limits(y = 0)

```

## 8.3 反转一条连续型坐标轴
```{r}
ggplot(PlantGrowth, aes(x = group, y = weight)) +
  geom_boxplot() +
  scale_y_reverse()

# 通过指定反序的范围产生类似的效果
ggplot(PlantGrowth, aes(x = group, y = weight)) +
  geom_boxplot() +
  ylim(6.5, 3.5)

```
```{r}
ggplot(PlantGrowth, aes(x = group, y = weight)) +
  geom_boxplot() +
  scale_y_reverse(limits = c(8, 0))

```

## 8.4 修改类别型坐标轴上项目的顺序
```{r}
pg_plot <- ggplot(PlantGrowth, aes(x = group, y = weight)) +
  geom_boxplot() 
pg_plot +
  scale_x_discrete(limits = c("trt1", "ctrl", "trt2"))

```
```{r}
pg_plot +
  scale_x_discrete(limits = c("ctrl", "trt1"))

```
```{r}
pg_plot +
  scale_x_discrete(limits = rev(levels(PlantGrowth$group)))

```

## 8.5 设置 x 轴和 y 轴的缩放比例
```{r}
library(gcookbook)  # 加载 gcookbook 是为了使用 marathon 数据集

m_plot <- ggplot(marathon, aes(x = Half, y = Full)) +
  geom_point() 

m_plot +
  coord_fixed()

```
```{r}
m_plot + 
  coord_fixed() + 
  scale_y_continuous(breaks = seq(0, 420, 30)) +
  scale_x_continuous(breaks = seq(0, 420, 30))

```
```{r}
m_plot +
  coord_fixed(ratio = 1/2) +
  scale_y_continuous(breaks = seq(0, 420, 30)) +
  scale_x_continuous(breaks = seq(0, 420, 30))

```

## 8.6 设置刻度线的位置
```{r}
ggplot(PlantGrowth, aes(x = group, y = weight)) +
  geom_boxplot()

ggplot(PlantGrowth, aes(x = group, y = weight)) +
  geom_boxplot() +
  scale_y_continuous(breaks = c(4, 4.25, 4.5, 5, 6, 8))

```
```{r}
seq(4, 7, by= .5)

```
```{r}
5:10

```
```{r}
# 为离散型坐标轴同时设定 breaks 和 limits
ggplot(PlantGrowth, aes(x = group, y = weight)) +
  geom_boxplot() +
  scale_x_discrete(limits = c("trt2", "ctrl"), breaks = "ctrl")

```

## 8.7 移除刻度线和标签
```{r}
pg_plot <- ggplot(PlantGrowth, aes(x = group, y = weight)) +
  geom_boxplot()

pg_plot +
  theme(axis.text.y = element_blank())

```
```{r}
pg_plot +
  theme(axis.ticks = element_blank(), axis.text.y = element_blank())

```
```{r}
pg_plot +
  scale_y_continuous(breaks = NULL)

```

## 8.8 修改刻度标签的文本
```{r}
library(gcookbook) # 加载 gcookbook，使用其中的 heightweight 数据集

hw_plot <- ggplot(heightweight, aes(x = ageYear, y = heightIn)) +
  geom_point()

hw_plot

```
```{r}
hw_plot +
  scale_y_continuous(
      breaks = c(50, 56, 60, 66, 72),
      labels = c("Tiny", "Really\nshort", "Short", "Medium", "Tallish")
  )

```
```{r}
footinch_formatter <- function(x) { 
  foot <- floor(x/12)
  inch <- x %% 12
  return(paste(foot, "'", inch, "\"", sep=""))
}

```
```{r}
footinch_formatter(56:64)

```
```{r}
hw_plot + 
  scale_y_continuous(labels = footinch_formatter)

```
```{r}
hw_plot + 
  scale_y_continuous(breaks = seq(48, 72, 4), labels = footinch_formatter)

```
```{r}
timeHMS_formatter <- function(x) { 
  h <- floor(x/60)
  m <- floor(x %% 60)
  s <- round(60*(x %% 1))                   # 舍入到最接近的秒数
  lab <- sprintf("%02d:%02d:%02d", h, m, s) # 格式化字符串为 HH:MM:SS 的格式
  lab <- gsub("^00:", "", lab)              # 如果开头存在 00: 则移除
  lab <- gsub("^0", "", lab)                # 如果开头存在 0 则移除
  return(lab)
}

```
```{r}
timeHMS_formatter(c(.33, 50, 51.25, 59.32, 60, 60.1, 130.23))

```

## 8.9 修改刻度标签的外观
```{r}
pg_plot <- ggplot(PlantGrowth, aes(x = group, y = weight)) +
  geom_boxplot() +
  scale_x_discrete(
    breaks = c("ctrl", "trt1", "trt2"),
    labels = c("Control", "Treatment 1", "Treatment 2")
  )

pg_plot

```
```{r}
pg_plot +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5))

```
```{r}
pg_plot +
  theme(axis.text.x = element_text(angle = 30, hjust = 1, vjust = 1))

```
```{r}
pg_plot +
  theme(
    axis.text.x = element_text(family = "Times", face = "italic",
                               colour = "darkred", size = rel(0.9))
  )

```

## 8.10 修改坐标轴标签的文本
```{r}
library(gcookbook) # 加载 gcookbook 是为了使用 heightweight 数据集

hw_plot <- ggplot(heightweight, aes(x = ageYear, y = heightIn, colour = sex)) + 
  geom_point()

# 使用默认的坐标轴标签
hw_plot

# 设置坐标轴标签
hw_plot +
  xlab("Age in years") +
  ylab("Height in inches")

```
```{r}
hw_plot +
  labs(x = "Age in years", y = "Height in inches")

```
```{r}
hw_plot +
  scale_x_continuous(name = "Age in years")

```
```{r}
hw_plot +
  scale_x_continuous(name = "Age\n(years)")

```

## 8.11 移除坐标轴标签
```{r}
pg_plot <- ggplot(PlantGrowth, aes(x = group, y = weight)) +
  geom_boxplot() 

pg_plot +
  xlab(NULL)

```
```{r}
pg_plot +
  xlab("")

```

## 8.12 修改坐标轴的外观
```{r}
library(gcookbook) # 加载 gcookbook 是为了使用 heightweight 数据集

hw_plot <- ggplot(heightweight, aes(x = ageYear, y = heightIn)) +
  geom_point()

hw_plot +
  theme(axis.title.x = element_text(face = "italic", colour = "darkred", 
                                    size = 14))

```
```{r}
hw_plot +
  ylab("Height\n(inches)") +
  theme(axis.title.y = element_text(angle = 0, face = "italic", size = 14))

```
```{r}
hw_plot +
  ylab("Height\n(inches)") +
  theme(axis.title.y = element_text(
    angle = 90,
    face = "italic",
    colour = "darkred",
    size = 14)
  )

```

## 8.13 沿坐标轴显示直线
```{r}
library(gcookbook) # 加载 gcookbook 是为了使用 heightweight 数据集

hw_plot <- ggplot(heightweight, aes(x = ageYear, y = heightIn)) +
  geom_point() 

hw_plot +
  theme(axis.line = element_line(colour = "black"))

```
```{r}
hw_plot +
  theme_bw() +
  theme(panel.border = element_blank(), 
        axis.line = element_line(colour = "black"))

```
```{r}
# 对于较粗的线条，只有一半重叠
hw_plot +
  theme_bw() +
  theme(
    panel.border = element_blank(),
    axis.line = element_line(colour = "black", size = 4)
  )

# 完全重叠
hw_plot + 
  theme_bw() +
  theme(
    panel.border = element_blank(),
    axis.line = element_line(colour = "black", size = 4, lineend = "square")
  )

```

## 8.14 使用对数坐标轴
```{r}
library(MASS) # 加载MASS，使用其中的 Animals 数据集

# 创建基本图形
animals_plot <- ggplot(Animals, aes(x = body, y = brain,     
                                    label = rownames(Animals))) +
  geom_text(size = 3)

animals_plot

# 使用对数 x 标度和对数 y 标度
animals_plot +
  scale_x_log10() +
  scale_y_log10()

```
```{r}
Animals
#>                      body  brain
#> Mountain beaver     1.350    8.1
#> Cow               465.000  423.0
#> Grey wolf          36.330  119.5
#>  ...<22 more rows>...
#> Brachiosaurus   87000.000  154.5
#> Mole                0.122    3.0
#> Pig               192.000  180.0

```
```{r}
10^(0:3)

```
```{r}
10^(-1:5)

```
```{r}
animals_plot +
  scale_x_log10(breaks = 10^(-1:5)) +
  scale_y_log10(breaks = 10^(0:3))

```
```{r}
library(scales)
animals_plot +
  scale_x_log10(breaks = 10^(-1:5),
                labels = trans_format("log10", math_format(10^.x))) +
  scale_y_log10(breaks = 10^(0:3),
                labels = trans_format("log10", math_format(10^.x)))

```
```{r}
ggplot(Animals, aes(x = log10(body), y = log10(brain),  
                    label = rownames(Animals))) +
  geom_text(size = 3)

```
```{r}
library(scales)

# 对 x 使用自然对数变换，对 y 使用 log2 变换
animals_plot +
  scale_x_continuous(
    trans = log_trans(),
    breaks = trans_breaks("log", function(x) exp(x)), 
    labels = trans_format("log", math_format(e^.x))
  ) +
  scale_y_continuous(
    trans = log2_trans(),
    breaks = trans_breaks("log2", function(x) 2^x), 
    labels = trans_format("log2", math_format(2^.x))
  )

```
```{r}
library(gcookbook) # 加载 gcookbook 是为了使用 aapl 数据集

ggplot(aapl, aes(x = date,y = adj_price)) +
  geom_line() 

ggplot(aapl, aes(x = date,y = adj_price)) +
  geom_line() +
  scale_y_log10(breaks = c(2, 10, 50, 250))

```

## 8.15 为对数坐标轴添加刻度
```{r}
library(MASS)   # 加载MASS，使用其中的 Animals 数据集
library(scales) # 为了使用 trans_format 相关函数

# 给定一个向量x，返回一个10的幂次的向量，包含x的所有值
breaks_log10 <- function(x) {
  low <- floor(log10(min(x)))
  high <- ceiling(log10(max(x)))
  
  10^(seq.int(low, high))
}

ggplot(Animals, aes(x = body, y = brain, label = rownames(Animals))) +
  geom_text(size=3) +
  annotation_logticks() +
  scale_x_log10(breaks = breaks_log10, 
                labels = trans_format(log10, math_format(10^.x))) +
  scale_y_log10(breaks = breaks_log10, 
                labels = trans_format(log10, math_format(10^.x)))

```
```{r}
breaks_log10(c(0.12, 6))

```
```{r}
breaks_5log10 <- function(x) {
  low <- floor(log10(min(x)/5))
  high <- ceiling(log10(max(x)/5))
  
  5 * 10^(seq.int(low, high))
}

breaks_5log10(c(0.12, 6))

```
```{r}
ggplot(Animals, aes(x = body, y = brain, label = rownames(Animals))) +
  geom_text(size = 3) +
  annotation_logticks() +
  scale_x_log10(breaks = breaks_log10, 
                minor_breaks = breaks_5log10,
                labels = trans_format(log10, math_format(10^.x))) +
  scale_y_log10(breaks = breaks_log10, 
                minor_breaks = breaks_5log10,
                labels = trans_format(log10, math_format(10^.x))) +
  coord_fixed() +
  theme_bw()

```

## 8.16 绘制环状图形
```{r}
library(gcookbook) # 加载 gcookbook 是为了使用 wind 数据集
wind
#>     TimeUTC Temp WindAvg WindMax WindDir SpeedCat DirCat
#> 3         0 3.54    9.52   10.39      89    10-15     90
#> 4         5 3.52    9.10    9.90      92     5-10     90
#> 5        10 3.53    8.73    9.51      92     5-10     90
#>  ...<280 more rows>...
#> 286    2335 6.74   18.98   23.81     250      >20    255
#> 287    2340 6.62   17.68   22.05     252      >20    255
#> 288    2345 6.22   18.54   23.91     259      >20    255

```
```{r}
ggplot(wind, aes(x = DirCat, fill = SpeedCat)) +
  geom_histogram(binwidth = 15, origin = -7.5) +
  coord_polar() +
  scale_x_continuous(limits = c(0, 360))

```
```{r}
ggplot(wind, aes(x = DirCat, fill = SpeedCat)) +     
  geom_histogram(binwidth = 15, boundary=-7.5, colour = "black", size = .25) +
  guides(fill = guide_legend(reverse = TRUE)) +
  coord_polar() +
  scale_x_continuous(limits = c(0,360), 
                     breaks = seq(0, 360, by = 45),
                     minor_breaks = seq(0, 360, by = 15)) + 
  scale_fill_brewer()

```
```{r}
coord_polar(start = -45 * pi / 180)

```
```{r}
# 将 mdeaths 的时间序列数据放入一个数据框
mdeaths_mod <- data.frame(
  deaths = as.numeric(mdeaths),
  month = as.numeric(cycle(mdeaths))
)

# 计算每个月的平均死亡数量
library(dplyr) 
mdeaths_mod <- mdeaths_mod %>%
  group_by(month) %>%
  summarise(deaths = mean(deaths))

mdeaths_mod
#> # A tibble: 12 x 2
#>   month    deaths
#>   <dbl>     <dbl>
#> 1     1  2129.833
#> 2     2  2081.333
#> 3     3  1970.500
#> 4     4  1657.333
#> 5     5  1314.167
#> 6     6  1186.833
#> 7     7  1136.667
#> 8     8  1037.667
#>  ... with 4 more rows

# 绘制基本图形
mdeaths_plot <- ggplot(mdeaths_mod, aes(x = month, y = deaths)) +
  geom_line() +
  scale_x_continuous(breaks = 1:12)

# 使用 coord_polar
mdeaths_plot + coord_polar()

```
```{r}
# 使用 coord_polar 并将 y (r) 的下界设置为 0
mdeaths_plot +
  coord_polar() +
  ylim(0, max(mdeaths_mod$deaths))

```
```{r}
mdeaths_plot +
  coord_polar() +
  ylim(0, max(mdeaths_mod$deaths)) +
  xlim(0, 12)

```
```{r}
# 通过添加一个值与 12 的值相同的 0 来连接曲线
mdeaths_x <- mdeaths_mod[mdeaths_mod$month==12, ] 
mdeaths_x$month <- 0
mdeaths_new <- rbind(mdeaths_x, mdeaths_mod)

# 通过使用 %+% ，绘制与之前相同的图形，只是使用的数据不同
mdeaths_plot %+% 
  mdeaths_new +
  coord_polar() +
  ylim(0, max(mdeaths_mod$deaths))

```

## 8.17 在坐标轴上使用日期
```{r}
economics
#> # A tibble: 574 x 6
#>   date         pce    pop psavert uempmed unemploy
#>   <date>     <dbl>  <int>   <dbl>   <dbl>    <int>
#> 1 1967-07-01  507. 198712    12.5     4.5     2944
#> 2 1967-08-01  510. 198911    12.5     4.7     2945
#> 3 1967-09-01  516. 199113    11.7     4.6     2958
#> 4 1967-10-01  513. 199311    12.5     4.9     3143
#> 5 1967-11-01  518. 199498    12.5     4.7     3066
#> 6 1967-12-01  526. 199657    12.1     4.8     3018
#> # ... with 568 more rows

```
```{r}
ggplot(economics, aes(x = date, y = psavert)) +
  geom_line()

```
```{r}
library(dplyr)

# 取 economics 的一个子集
econ_mod <- economics %>% 
  filter(date >= as.Date("1992-05-01") & date < as.Date("1993-06-01"))

# 创建一个不指定分割点的基本图形
econ_plot <- ggplot(econ_mod, aes(x = date, y = psavert)) +
  geom_line()

econ_plot

```
```{r}
# 指定一个日期向量为分割点
datebreaks <- seq(as.Date("1992-06-01"), as.Date("1993-06-01"), by = "2 month")

# 使用分割点并旋转文本标签
econ_plot +
  scale_x_date(breaks = datebreaks) +
  theme(axis.text.x = element_text(angle = 30, hjust = 1))

```
```{r}
library(scales)

econ_plot +
  scale_x_date(breaks = datebreaks, labels = date_format("%Y %b")) +
  theme(axis.text.x = element_text(angle = 30, hjust = 1))

```
```{r}
# Mac 和 Linux
Sys.setlocale("LC_TIME", "it_IT.UTF-8")

# Windows
Sys.setlocale("LC_TIME", "italian")

```

## 8.18 在坐标轴上使用相对时间
```{r}
# 转换时间序列对象 WWWusage 为数据框
www <- data.frame(
  minute = as.numeric(time(WWWusage)),
  users = as.numeric(WWWusage)
)

#  定义一个格式刷函数—可将以分钟表示的时间转换为字符串
timeHM_formatter <- function(x) {
  h <- floor(x/60)
  m <- floor(x %% 60)
  lab <- sprintf("%d:%02d", h, m) # 将字符串格式化为 HH:MM（时 : 分）的格式
  return(lab)
}

# 默认的 x 轴
ggplot(www, aes(x = minute, y = users)) +
  geom_line()

# 使用格式化后的时间
ggplot(www, aes(x = minute, y = users)) +
  geom_line() +
  scale_x_continuous(
    name = "time",
    breaks = seq(0, 100, by = 10),
    labels = timeHM_formatter
  )

```
```{r}
scale_x_continuous(
  breaks = c(0, 20, 40, 60, 80, 100),
  labels = c("0:00", "0:20", "0:40", "1:00", "1:20", "1:40")
)

```
```{r}
timeHM_formatter(c(0, 50, 51, 59, 60, 130, 604))

```
```{r}
timeHMS_formatter <- function(x) { 
  h <- floor(x/3600)
  m <- floor((x/60) %% 60)
  s <- round(x %% 60)                         # 舍入到最接近的秒数
  lab <- sprintf("%02d:%02d:%02d", h, m, s) # 格式化字符串为 HH:MM:SS 的格式
  lab <- sub("^00:", "", lab)                 # 如果开头存在 00: 则移除
  lab <- sub("^0", "", lab)                 # 如果开头存在 0 则移除
  return(lab)
}

```
```{r}
timeHMS_formatter(c(20, 3000, 3075, 3559.2, 3600, 3606, 7813.8))

```

