# Chapter 14 输出图形用以展示

## 14.1 输出为 PDF 矢量文件
```{r}
# width（宽度）和 height（高度）的单位为英寸
pdf("myplot.pdf", width = 4, height = 4)

# 绘制图形
plot(mtcars$wt, mtcars$mpg)
print(ggplot(mtcars, aes(x = wt, y = mpg)) + geom_point())

dev.off()

```
```{r}
# 8×8 cm
pdf("myplot.pdf", width = 8/2.54, height = 8/2.54)

```
```{r}
plot1 <- ggplot(mtcars, aes(x = wt, y = mpg)) +
    geom_point()

# 默认单位为英寸，不过也可指定单位
ggsave("myplot.pdf", plot1, width = 8, height = 8, units = "cm")

```
```{r}
ggplot(mtcars, aes(x = wt, y = mpg)) +
    geom_point()

ggsave("myplot.pdf", width = 8, height = 8, units = "cm")

```

## 14.2 输出为 SVG 矢量文件
```{r, eval=FALSE}
install.packages("svglite")
library(svglite)
svglite("myplot.svg", width = 4, height = 4)
plot(mtcars$wt, mtcars$mpg)
dev.off()

# 使用 ggsave()
ggsave("myplot.svg", width = 8, height = 8, units = "cm")

```

## 14.3 输出为 WMF 矢量文件
```{r, eval=FALSE}
# 只在 windows 平台下可用
win.metafile("myplot.wmf", width = 4, height = 4) 
plot(mtcars$wt, mtcars$mpg)
dev.off()

# 使用 ggsave()
ggsave("myplot.wmf", width = 8, height = 8, units = "cm")

```

## 14.4 编辑矢量格式的输出文件
```{r, eval=FALSE}
pdf("myplot.pdf", width = 4, height = 4, useDingbats = FALSE)

# 或者
ggsave("myplot.pdf", width = 4, height = 4, useDingbats = FALSE)

```

## 14.5 输出为点阵（PNG/TIFF）文件
```{r}
# width（宽度）和 height（高度）的单位为像素
png("myplot.png", width = 400, height = 400)

# 绘制图形
plot(mtcars$wt, mtcars$mpg)

dev.off()

```
```{r}
# width（宽度）和 height（高度）的单位为像素
png("myplot-%d.png", width = 400, height = 400)

plot(mtcars$wt, mtcars$mpg)
print(ggplot(mtcars, aes(x = wt, y = mpg)) + geom_point())

dev.off()

```
```{r}
ppi <- 300
# 计算一幅 4 英寸 ×4 英寸 300 ppi 图像的高度和宽度（以像素为单位）

png("myplot.png", width = 4*ppi, height = 4*ppi, res = ppi) 
plot(mtcars$wt, mtcars$mpg)
dev.off()

```
```{r}
library(ggplot2)
ggplot(mtcars, aes(x = wt, y = mpg)) + geom_point()

# 默认的宽高单位是英寸，不过也可以指定其他单位
ggsave("myplot.png", width = 8, height = 8, unit = "cm", dpi = 300)

```
```{r}
install.packages("Cairo") # 只需安装一次
library(Cairo)
CairoPNG("myplot.png") 
plot(mtcars$wt, mtcars$mpg)
dev.off()

```

## 14.6 在 PDF 文件中使用字体
```{r}
install.packages("extrafont") 
library(extrafont)

# 查找并保存系统中已安装字体的信息
font_import()

# 列出字体
fonts()

```
```{r}
library(extrafont)
# 在 R 中注册字体
loadfonts()

# 在 Windows 上，你可能需要指定 Ghostscript 的安装位置
#（根据你的 Ghostscript 安装位置调整对应的路径）
Sys.setenv(R_GSCMD = "C:/Program Files/gs/gs9.05/bin/gswin32c.exe")

```
```{r}
library(ggplot2)
ggplot(mtcars, aes(x = wt, y = mpg)) + geom_point() + 
    ggtitle("Title text goes here") +
    theme(text = element_text(size = 16, family = "Impact"))

 ggsave("myplot.pdf", width = 4, height = 4) 

 embed_fonts("myplot.pdf")

```

## 14.7 在 Windows 的点阵或屏幕输出中使用字体
```{r}
install.packages("extrafont") 
library(extrafont)

# 查找并保存系统中已安装字体的信息
font_import()

# 列出字体
fonts()

```
```{r}
library(extrafont)
# 注册 Windows 中的字体
loadfonts("win")

```
```{r}
library(ggplot2)
ggplot(mtcars, aes(x = wt, y = mpg)) + geom_point() + 
    ggtitle("Title text goes here") +
    theme(text = element_text(size = 16, family = "Georgia", face = "italic")) 

ggsave("myplot.png", width = 4, height = 4, dpi = 300)

```

## 14.8 混合多个图
```{r}
install.packages("devtools")
devtools::install_github("thomasp85/patchwork")

```
```{r}
library(patchwork)

plot1 <- ggplot(PlantGrowth, aes(x = weight)) +
    geom_histogram(bins = 12)

plot2 <- ggplot(PlantGrowth, aes(x = group, y = weight, group = group)) +
    geom_boxplot()

plot1 + plot2

```
```{r}
plot3 <- ggplot(PlantGrowth, aes(x = weight, fill = group)) +
    geom_density(alpha = 0.25)

plot1 + plot2 + plot3 +
    plot_layout(ncol = 2)

```
```{r}
plot1 + plot2 +
    plot_layout(ncol = 1, heights = c(1, 4))

```

