# Chapter 15 数据塑形

## 15.1 创建数据框
```{r}
# 从两个简单的向量开始
g <- c("A", "B", "C")
x <- 1:3

dat <- data.frame(g, x) 
dat
#>   g x
#> 1 A 1
#> 2 B 2
#> 3 C 3

```
```{r}
lst <- list(group = g, value = x) # 由向量组成的列表

dat <- as.data.frame(lst)

```
```{r}
library(dplyr)
data_frame(g, x)
#> # A tibble: 3 x 2
#>   g         x
#>  <chr>  <int>
#> 1 A         1
#> 2 B         2
#> 3 C         3

# 将在列表中的向量转换成 tibble
as_data_frame(lst)

```
```{r}
as_tibble(dat)
#> # A tibble: 3 x 2
#>  group value
#>  <fct> <int>
#> 1 A        1
#> 2 B        2
#> 3 C        3

```

## 15.2 从数据框中提取信息
```{r}
str(ToothGrowth)
#> 'data.frame':    60 obs. of  3 variables:
#>  $ len : num  4.2 11.5 7.3 5.8 6.4 10 11.2 11.2 5.2 7 ...
#>  $ supp: Factor w/ 2 levels "OJ","VC": 2 2 2 2 2 2 2 2 2 2 ...
#>  $ dose: num  0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 ...

```
```{r}
summary(ToothGrowth)
#>       len        supp         dose      
#>  Min.   : 4.20   OJ:30   Min.   :0.500  
#>  1st Qu.:13.07   VC:30   1st Qu.:0.500  
#>  Median :19.25           Median :1.000  
#>  Mean   :18.81           Mean   :1.167  
#>  3rd Qu.:25.27           3rd Qu.:2.000  
#>  Max.   :33.90           Max.   :2.000

```
```{r}
tg <- ToothGrowth
tg$supp <- as.character(tg$supp)

str(tg)
#> 'data.frame': 60 obs. of 3 variables:
#> $ len : num 4.2 11.5 7.3 5.8 6.4 10 11.2 11.2 5.2 7 ...
#> $ supp: chr "VC" "VC" "VC" "VC" ...
#> $ dose: num 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 ...

# 直接输出列
# 原始数据框 (因子)
ToothGrowth$supp
#> [1] VC VC VC VC VC VC VC VC VC VC VC VC VC VC VC VC VC VC VC VC VC VC VC VC
#> [25] VC VC VC VC VC VC OJ OJ OJ OJ OJ OJ OJ OJ OJ OJ OJ OJ OJ OJ OJ OJ OJ OJ
#> [49] OJ OJ OJ OJ OJ OJ OJ OJ OJ OJ OJ OJ
#> Levels: OJ VC

# 新数据框 (字符串)
tg$supp
tg$supp
#> [1] "VC" "VC" "VC" "VC" "VC" "VC" "VC" "VC" "VC" "VC" "VC" "VC" "VC" "VC"
#> [15] "VC" "VC" "VC" "VC" "VC" "VC" "VC" "VC" "VC" "VC" "VC" "VC" "VC" "VC"
#> [29] "VC" "VC" "OJ" "OJ" "OJ" "OJ" "OJ" "OJ" "OJ" "OJ" "OJ" "OJ" "OJ" "OJ"
#> [43] "OJ" "OJ" "OJ" "OJ" "OJ" "OJ" "OJ" "OJ" "OJ" "OJ" "OJ" "OJ" "OJ" "OJ"
#> [57] "OJ" "OJ" "OJ" "OJ"

```

## 15.3 向数据框添加列
```{r}
library(dplyr)
ToothGrowth %>%
    mutate(newcol = NA)

```
```{r}
vec <- rep(c(1, 2), 30)

ToothGrowth %>%
    mutate(newcol = vec)

```
```{r}
# 为了本例使用而复制一个 ToothGrowth 
ToothGrowth2 <- ToothGrowth

# 给一整列赋值 NA
ToothGrowth2$newcol <- NA

# 赋值 1 和 2，自动重复赋值来填充此列
ToothGrowth2$newcol <- c(1, 2)

```

## 15.4 从数据框中删除一列
```{r}
# 移除 len 列
ToothGrowth %>%
    select(-len)

```
```{r}
# 从 ToothGrowth 中删除 len 和 supp 列
ToothGrowth %>%
    select(-len, -supp)

# 只保留 dose 列
ToothGrowth %>%
    select(dose)    

```
```{r}
ToothGrowth$len <- NULL

```

## 15.5 重命名数据框的列名
```{r}
tg_mod <- ToothGrowth %>%
      rename(length = len)

```
```{r}
ToothGrowth %>%
    rename(length = len, 
           supplement_type = supp
    )
#>   length supplement_type dose
#> 1    4.2              VC  0.5
#> 2   11.5              VC  0.5
#>  ...<56 more rows>...
#> 59  29.4              OJ  2.0
#> 60  23.0              OJ  2.0

```
```{r}
# 复制 ToothGrowth 数据
ToothGrowth2 <- ToothGrowth

names(ToothGrowth2)  # 输出列名
#> [1] "len" "supp" "dose"

names(ToothGrowth2)[names(ToothGrowth2) == "len"] <- "length"

names(ToothGrowth)
#> [1] "len" "supp" "dose"

```

## 15.6 重排序数据框的列
```{r}
ToothGrowth %>%
    select(dose, len, supp)
#>   dose  len supp
#> 1    0.5  4.2    VC
#> 2    0.5 11.5    VC
#>  ...<56 more rows>...
#> 59 2.0 29.4  OJ
#> 60 2.0 23.0  OJ

```
```{r}
ToothGrowth %>%
    select(dose, everything())
#>   dose  len supp
#> 1    0.5  4.2    VC
#> 2    0.5 11.5    VC
#> ...<56 more rows>...
#> 59 2.0 29.4  OJ
#> 60 2.0 23.0  OJ

```
```{r}
ToothGrowth[c("dose", "len", "supp")]

```
```{r}
ToothGrowth[, c("dose", "len", "supp")] # 矩阵风格的索引

```
```{r}
ToothGrowth["dose"]
#>   dose
#> 1    0.5
#> 2    0.5
#>  ...<56 more rows>...
#> 59 2.0
#> 60 2.0

ToothGrowth[, "dose"]
#> [1] 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0
#> [19] 1.0 1.0 2.0 2.0 2.0 2.0 2.0 2.0 2.0 2.0 2.0 2.0 0.5 0.5 0.5 0.5 0.5 0.5
#> [37] 0.5 0.5 0.5 0.5 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 2.0 2.0 2.0 2.0
#> [55] 2.0 2.0 2.0 2.0 2.0 2.0

```
```{r}
ToothGrowth[, "dose", drop=FALSE]
#>   dose
#> 1    0.5
#> 2    0.5
#>  ...<56 more rows>...
#> 59 2.0
#> 60 2.0

```

## 15.7 从数据框提取子集
```{r}
library(gcookbook) # 加载 gcookbook 是为了使用 climate 数据集
climate
#>      Source Year Anomaly1y Anomaly5y Anomaly10y Unc10y
#> 1  Berkeley 1800        NA        NA     -0.435  0.505
#> 2  Berkeley 1801        NA        NA     -0.453  0.493
#>  ...<495 more rows>...
#> 498 CRUTEM3 2010    0.8023        NA         NA     NA
#> 499 CRUTEM3 2011    0.6193        NA         NA     NA

```
```{r}
climate %>%
    filter(Source == "Berkeley" & Year >= 1900 & Year <= 2000)

```
```{r}
climate %>%
    select(Year, Anomaly10y)
#>     Year Anomaly10y
#> 1   1800     -0.435
#> 2   1801     -0.453
#>  ...<495 more rows>...
#> 498 2010         NA
#> 499 2011         NA

```
```{r}
climate %>%
  filter(Source == "Berkeley" & Year >= 1900 & Year <= 2000) %>%
  select(Year, Anomaly10y)
#>     Year Anomaly10y
#> 1   1900     -0.171
#> 2   1901     -0.162
#>  ...<97 more rows>...
#> 100 1999      0.734
#> 101 2000      0.748

```
```{r}
slice(climate, 1:100)

```
```{r}
climate[climate$Source == "Berkeley" & 
        climate$Year >= 1900 & 
        climate$Year <= 2000, ]
#>       Source Year Anomaly1y Anomaly5y Anomaly10y Unc10y
#> 101 Berkeley 1900        NA        NA     -0.171  0.108
#> 102 Berkeley 1901        NA        NA     -0.162  0.109
#>  ...<97 more rows>...
#> 200 Berkeley 1999        NA        NA      0.734  0.025
#> 201 Berkeley 2000        NA        NA      0.748  0.026

```
```{r}
climate[climate$Source == "Berkeley" &
        climate$Year >= 1900 &
        climate$Year <= 2000,
        c("Year", "Anomaly10y")]
#>     Year Anomaly10y
#> 101 1900     -0.171
#> 102 1901     -0.162
#>  ...<97 more rows>...
#> 200 1999      0.734
#> 201 2000      0.748

```

## 15.8 改变因子水平的顺序
```{r}
# 默认的因子水平的顺序是按字母排的
sizes <- factor(c("small", "large", "large", "small", "medium")) 
sizes
#> [1] small large large small medium
#> Levels: large medium small

# 改变因子水平的顺序
factor(sizes, levels = c("small", "medium", "large"))
#> [1] small large large small medium
#> Levels: small medium large

```
```{r}
factor(c("small", "large", "large", "small", "medium"), 
       levels = c("small", "medium", "large"))

```
```{r}
factor(sizes, levels = rev(levels(sizes)))

```
```{r}
# 改变水平的顺序
library(forcats)
fct_relevel(sizes, "small", "medium", "large")
#> [1] small large large small medium
#> Levels: small medium large

```

## 15.9 根据数据的值改变因子水平的顺序
```{r}
# 复制一份 InsectSprays 数据，因为我们要修改它 
iss <- InsectSprays 
iss$spray
#> [1] A A A A A A A A A A A A B B B B B B B B B B B B C C C C C C C C C C C C
#> [37] D D D D D D D D D D D D E E E E E E E E E E E E F F F F F F F F F F F F
#> Levels: A B C D E F

iss$spray <- reorder(iss$spray, iss$count, FUN=mean) 
iss$spray
#> [1] A A A A A A A A A A A A B B B B B B B B B B B B C C C C C C C C C C C C
#> [37] D D D D D D D D D D D D E E E E E E E E E E E E F F F F F F F F F F F F
#> attr(,"scores")
#>         A         B        C        D        E         F
#> 14.500000 15.333333 2.083333 4.916667 3.500000 16.666667
#> Levels: C E D A B F

```
```{r}
install.packages("forcats")
library(forcats)
reorder(iss$spray, iss$count, FUN = mean)
fct_reorder(iss$spray, iss$count, .fun = mean)

```

## 15.10 改变因子水平的名称
```{r}
sizes <- factor(c( "small", "large", "large", "small", "medium"))
sizes
#> [1] small large large small medium
#> Levels: large medium small

# 通过一个命名向量传入映射关系（旧水平跟新水平的映射）
fct_recode(sizes, S = "small", M = "medium", L = "large")
#> [1] S L L S M
#> Levels: L M S

```
```{r}
old <- c("small", "medium", "large")
new <- c("S", "M", "L")

# 创建一个表示新旧映射关系的命名变量
mappings <- setNames(old, new)
mappings
#>  S   M   L
#> "small" "medium" "large"

# 创建传给 fct_recode() 的参数列表
args <- c(list(sizes), mappings)

# 观察这个列表的结构
str(args)
#> List of 4
#> $ : Factor w/ 3 levels "large","medium",..: 3 1 1 3 2
#> $ S: chr "small"
#> $ M: chr "medium"
#> $ L: chr "large"

# do.call 传入参数，调用 fct_recode 
do.call(fct_recode, args)
#> [1] S L L S M
#> Levels: L M S

```
```{r}
do.call(
    fct_recode,
    c(list(sizes), setNames(c("small", "medium", "large"), c("S", "M", "L")))
)
#> [1] S L L S M
#> Levels: L M S

```
```{r}
sizes <- factor(c( "small", "large", "large", "small", "medium"))

# 逐个重命名因子水平水平
levels(sizes)[levels(sizes) == "large"] <- "L" 
levels(sizes)[levels(sizes) == "medium"] <- "M" 
levels(sizes)[levels(sizes) == "small"] <- "S" 

sizes
#> [1] S L L S M
#> Levels: L M S

```
```{r}
sizes <- factor(c("small", "large", "large", "small", "medium")) 
levels(sizes) <- list(S = "small", M = "medium", L = "large")
sizes
#> [1] S L L S M
#> Levels: S M L

```
```{r}
sizes <- factor(c("small", "large", "large", "small", "medium"))
levels(sizes)[1] <- "L" 
sizes
#> [1] small L L small medium
#> Levels: L medium small

# 同时重命名所有因子水平 
levels(sizes) <- c("L", "M", "S") 
sizes
#> [1] S L L S M
#> Levels: L M S

```

## 15.11 去掉因子中不再使用的水平
```{r}
sizes <- factor(c("small", "large", "large", "small", "medium")) 
sizes <- sizes[1:3]
sizes
#> [1] small large large
#> Levels: large medium small

```
```{r}
droplevels(sizes)
#> [1] small large large
#> Levels: large small

```
```{r}
fct_drop(sizes)
#> [1] small large large
#> Levels: large small

```

## 15.12 在字符向量中改变元素的名称
```{r}
sizes <- c("small", "large", "large", "small", "medium") 
sizes
#> [1] "small" "large" "large" "small" "medium"

# 通过函数 recode()，传递一组映射关系
recode(sizes, small = "S", medium = "M", large = "L")
#> [1] "S" "L" "L" "S" "M"

# 也可以使用引号 — 如果原因子水平名称中存在空格等特殊字符，这将很有用
recode(sizes, "small" = "S", "medium" = "M", "large" = "L")
#> [1] "S" "L" "L" "S" "M"

```
```{r}
old <- c("small", "medium", "large")
new <- c("S", "M", "L")
# 创建一个命名向量表示新旧水平之间的映射关系
mappings <- setNames(new, old)
mappings
#> small medium large
#>  "S" "M" "L"

# 创建一列传给 fct_recode 的参数值
args <- c(list(sizes), mappings)
# 观察这个列表的结构
str(args)
#> List of 4
#> $    : chr [1:5] "small" "large" "large" "small" ...
#> $ small : chr "S"
#> $ medium: chr "M"
#> $ large : chr "L"
# 通过 do.call() 调用 recode

do.call(fct_recode, args)
#> [1] "S" "L" "L" "S" "M"

```
```{r}
do.call(
    recode,
    c(list(sizes), setNames(c("S", "M", "L"), c("small", "medium", "large")))
)
#> [1] "S" "L" "L" "S" "M"

```
```{r}
sizes <- c("small", "large", "large", "small", "medium")
sizes[sizes == "small"] <- "S"
sizes[sizes == "medium"] <- "M" 
sizes[sizes == "large"] <- "L" 
sizes
#> [1] "S" "L" "L" "S" "M"

```

## 15.13 把一个分类变量转化成另一个分类变量
```{r}
# 在 PlantGrowth 的一个子数据集上操作
pg <- PlantGrowth[c(1,2,11,21,22), ] 
pg
#>  weight group
#> 1  4.17  ctrl
#> 2  5.58  ctrl
#> 11 4.81  trt1
#> 21 6.31  trt2
#> 22 5.12  trt2

```
```{r}
library(dplyr)

recode(pg$group, ctrl = "No", trt1 = "Yes", trt2 = "Yes")
#> [1] No No Yes Yes Yes
#> Levels: No Yes

```
```{r}
pg$treatment <- recode(pg$group, ctrl = "No", trt1 = "Yes", trt2 = "Yes")

```
```{r}
recode(as.character(pg$group), ctrl = "No", trt1 = "Yes", trt2 = "Yes")
#> [1] "No" "No" "Yes" "Yes" "Yes"

```
```{r}
library(forcats)
fct_recode(pg$group, No = "ctrl", Yes = "trt1", Yes = "trt2")
#> [1] No No Yes Yes Yes
#> Levels: No Yes

```
```{r}
oldvals <- c("ctrl", "trt1", "trt2")
newvals <- factor(c("No", "Yes", "Yes"))

newvals[ match(pg$group, oldvals) ]
#> [1] No No Yes Yes Yes
#> Levels: No Yes

```
```{r}
pg$treatment[pg$group == "ctrl"] <- "No" 
pg$treatment[pg$group == "trt1"] <- "Yes" 
pg$treatment[pg$group == "trt2"] <- "Yes"

# Convert to a factor
pg$treatment <- factor(pg$treatment)
pg
#>  weight group treatment
#> 1  4.17  ctrl        No
#> 2  5.58  ctrl        No
#> 11 4.81  trt1       Yes
#> 21 6.31  trt2       Yes
#> 22 5.12  trt2       Yes

```
```{r}
pg$newcol[pg$group == "ctrl" & pg$weight < 5] <- "no_small" 
pg$newcol[pg$group == "ctrl" & pg$weight >= 5] <- "no_large" 
pg$newcol[pg$group == "trt1"] <- "yes"
pg$newcol[pg$group == "trt2"] <- "yes" 
pg$newcol <- factor(pg$newcol)
pg
#>   weight group  newcol
#> 1   4.17 ctrl no_small
#> 2   5.58 ctrl no_large
#> 11  4.81 trt1     yes
#> 21  6.31 trt2     yes
#> 22  5.12 trt2     yes

```
```{r}
pg$weightgroup <- interaction(pg$weight, pg$group)
pg
#>    weight group weightgroup
#>  1   4.17  ctrl   4.17.ctrl
#>  2   5.58  ctrl   5.58.ctrl
#>  11  4.81  trt1   4.81.trt1
#>  21  6.31  trt2   6.31.trt2
#>  22  5.12  trt2   5.12.trt2

```

## 15.14 连续变量转变为分类变量
```{r}
pg <- PlantGrowth
pg$wtclass <- cut(pg$weight, breaks = c(0, 5, 6, Inf))
pg
#>   weight group wtclass
#> 1  4.17   ctrl   (0,5]
#> 2  5.58   ctrl   (5,6]
#>  ...<26 more rows>...
#> 29 5.80   trt2   (5,6]
#> 30 5.26   trt2   (5,6]

```
```{r}
pg$wtclass <- cut(pg$weight, breaks = c(0, 5, 6, Inf),
                  labels = c("small", "medium", "large")) 
pg
#>  weight group wtclass
#> 1  4.17  ctrl   small
#> 2  5.58  ctrl  medium
#>  ...<26 more rows>...
#> 29 5.80  trt2  medium
#> 30 5.26  trt2  medium

```
```{r}
cut(pg$weight, breaks = c(0, 5, 6, Inf), right = FALSE)
#> [1] [0,5)    [5,6)   [5,6)   [6,Inf) [0,5)   [0,5)   [5,6)   [0,5)   [5,6)
#> [10] [5,6)   [0,5)   [0,5)   [0,5)   [0,5)   [5,6)   [0,5)   [6,Inf) [0,5)
#> [19] [0,5)   [0,5)   [6,Inf) [5,6)   [5,6)   [5,6)   [5,6)   [5,6)   [0,5)
#> [28] [6,Inf) [5,6)   [5,6)
#> Levels: [0,5) [5,6) [6,Inf)

```

## 15.15 通过已有的列计算新的列
```{r}
library(gcookbook) # 加载 gcookbook 是为了使用 heightweight 数据集
heightweight
#>     sex ageYear ageMonth heightIn weightLb
#>  1    f   11.92      143     56.3     85.0
#>  2    f   12.92      155     62.3    105.0
#>   ...<232 more rows>...
#>  236  m   13.92      167     62.0    107.5
#>  237  m   12.58      151     59.3     87.0

```
```{r}
heightweight %>%
    mutate(heightCm = heightIn * 2.54)
#>      sex ageYear ageMonth heightIn weightLb heightCm
#>  1     f   11.92      143     56.3     85.0  143.002
#>  2     f   12.92      155     62.3    105.0  158.242
#>   ...<232 more rows>...
#>  235   m   13.92      167     62.0    107.5  157.480
#>  236   m   12.58      151     59.3     87.0  150.622

```
```{r}
heightweight %>%
    mutate(
        heightCm = heightIn * 2.54, 
        weightKg = weightLb / 2.204
    )
#>     sex ageYear ageMonth heightIn weightLb heightCm weightKg
#>  1    f   11.92      143     56.3     85.0  143.002 38.56624
#>  2    f   12.92      155     62.3    105.0  158.242 47.64065
#>  ...<232 more rows>...
#>  235  m   13.92      167     62.0    107.5  157.480 48.77495
#>  236  m   12.58      151     59.3     87.0  150.622 39.47368

```
```{r}
heightweight %>%
    mutate(bmi = weightKg / (heightCm / 100)^2)

```
```{r}
heightweight %>%
    mutate(
        heightCm = heightIn * 2.54, 
        weightKg = weightLb / 2.204,
        bmi = weightKg / (heightCm / 100)^2
    )
#>     sex ageYear ageMonth heightIn weightLb heightCm weightKg      bmi
#>  1    f   11.92      143     56.3     85.0  143.002 38.56624 18.85919
#>  2    f   12.92      155     62.3    105.0  158.242 47.64065 19.02542
#>   ...<232 more rows>...
#>  235  m   13.92      167     62.0    107.5  157.480 48.77495 19.66736
#>  236  m   12.58      151     59.3     87.0  150.622 39.47368 17.39926

```
```{r}
heightweight$heightCm <- heightweight$heightIn * 2.54

```

## 15.16 分组计算新列
```{r}
library(MASS) # 加载 MASS 是为了使用 cabbages 数据集
library(dplyr)
library(dplyr)

cabbages %>%
    group_by(Cult) %>%
    mutate(DevWt = HeadWt - mean(HeadWt))
#> # A tibble: 60 x 5
#> # Groups:    Cult [2]
#>  Cult  Date HeadWt  VitC  DevWt
#>  <fct> <fct> <dbl> <int>  <dbl>
#> 1 c39    d16     2.5    51 -0.407
#> 2 c39    d16     2.2    55 -0.707
#> 3 c39    d16     3.1    45  0.193
#> 4 c39    d16     4.3    42  1.39
#> 5 c39    d16     2.5    53 -0.407
#> 6 c39    d16     4.3    50  1.39
#> #  ... with 54 more rows

```
```{r}
cabbages
#>   Cult Date HeadWt VitC
#> 1  c39  d16    2.5   51
#> 2  c39  d16    2.2   55
#>  ...<56 more rows>...
#> 59 c52  d21    1.5   66
#> 60 c52  d21    1.6   72

```
```{r}
mutate(cabbages, DevWt = HeadWt - mean(HeadWt))
#>   Cult Date HeadWt VitC       DevWt
#> 1  c39  d16    2.5   51 -0.09333333
#> 2  c39  d16    2.2   55 -0.39333333
#> ...<56 more rows>...
#> 59 c52  d21    1.5   66 -1.09333333
#> 60 c52  d21    1.6   72 -0.99333333

```
```{r}
cb <- cabbages %>%
    group_by(Cult) %>%
    mutate(DevWt = HeadWt - mean(HeadWt))

```
```{r}
library(ggplot2)
# 标准化前
ggplot(cb, aes(x = Cult, y = HeadWt)) + 
  geom_boxplot()

# 标准化后
ggplot(cb, aes(x = Cult, y = DevWt)) + 
  geom_boxplot()

```
```{r}
cabbages %>%
    group_by(Cult, Date) %>%
        mutate(
            DevWt = HeadWt - mean(HeadWt), 
            DevVitC = VitC - mean(VitC)
        )
#> # A tibble: 60 x 6
#> # Groups:    Cult, Date [6]
#>   Cult Date HeadWt  VitC DevWt DevVitC
#>  <fct> <fct> <dbl> <int> <dbl>     <dbl>
#> 1 c39    d16     2.5    51 -0.68  0.7
#> 2 c39    d16     2.2    55 -0.98  4.7
#> 3 c39    d16     3.1    45 -0.08 -5.30
#> 4 c39    d16     4.3    42  1.12 -8.30
#> 5 c39    d16     2.5    53 -0.68  2.7
#> 6 c39    d16     4.3    50  1.12 -0.300
#> # ... with 54 more rows

```

## 15.17 分组汇总数据
```{r}
library(MASS) # 加载 MASS 是为了使用 cabbages 数据集
library(dplyr)

cabbages %>%
    group_by(Cult, Date) %>%
    summarise(
        Weight = mean(HeadWt), 
        VitC = mean(VitC)
    )
#> # A tibble: 6 x 4
#> # Groups:    Cult [?]
#>    Cult  Date Weight VitC
#>    <fct> <fct> <dbl> <dbl>
#>  1 c39   d16   3.18  50.3
#>  2 c39   d20   2.8   49.4
#>  3 c39   d21   2.74  54.8
#>  4 c52   d16   2.26  62.5
#>  5 c52   d20   3.11  58.9
#>  6 c52   d21   1.47  71.8

```
```{r}
cabbages
#>   Cult Date HeadWt VitC
#> 2  c39  d16    2.2   55
#>  ...<56 more rows>...
#> 59 c52  d21    1.5   66
#> 60 c52  d21    1.6   72

```
```{r}
library(dplyr)
summarise(cabbages, Weight = mean(HeadWt))
#>   Weight
#> 1 2.593333

```
```{r}
tmp <- group_by(cabbages, Cult)
summarise(tmp, Weight = mean(HeadWt))
#> # A tibble: 2 x 2
#>  Cult Weight
#>  <fct> <dbl>
#> 1 c39    2.91
#> 2 c52    2.28

```
```{r}
group_by(cabbages, Cult)
# 管道符号将 cabbages 用作 group_by() 的第一个参数
cabbages %>% group_by(Cult)

```
```{r}
summarise(group_by(cabbages, Cult), Weight = mean(HeadWt))

```
```{r}
cabbages %>% 
  group_by(Cult) %>% 
  summarise(Weight = mean(HeadWt))

```
```{r}
cabbages %>%
    group_by(Cult, Date) %>%
        summarise(
            Weight = mean(HeadWt), 
            Vitc = mean(VitC)
        )
#> # A tibble: 6 x 4
#> # Groups:    Cult [?]
#>   Cult   Date Weight Vitc
#>   <fct> <fct>  <dbl> <dbl>
#> 1 c39     d16  3.18  50.3
#> 2 c39     d20  2.8   49.4
#> 3 c39     d21  2.74  54.8
#> 4 c52     d16  2.26  62.5
#> 5 c52     d20  3.11  58.9
#> 6 c52     d21  1.47  71.8

```
```{r}
cabbages %>%
    group_by(Cult, Date) %>%
    summarise(
        Weight = mean(HeadWt), 
        sd = sd(HeadWt),
        n = n()
    )
#> # A tibble: 6 x 5
#> # Groups:    Cult [?]
#>   Cult   Date Weight   sd       n
#>   <fct> <fct> <dbl> <dbl> <int>
#> 1 c39     d16  3.18 0.957    10
#> 2 c39     d20  2.8  0.279    10
#> 3 c39     d21  2.74 0.983    10
#> 4 c52     d16  2.26 0.445    10
#> 5 c52     d20  3.11 0.791    10
#> 6 c52     d21  1.47 0.211    10

```
```{r}
c1 <- cabbages  # 复制数据
c1$HeadWt[c(1,20,45)] <- NA # 数据某些值赋值为 NA

c1 %>%
  group_by(Cult) %>%
  summarise(
      Weight = mean(HeadWt), 
      sd = sd(HeadWt),
      n = n()
  )
#> # A tibble: 2 x 4
#>   Cult Weight     sd     n
#>  <fct> <dbl> <dbl> <int>
#> 1 c39    NA    NA     30
#> 2 c52    NA    NA     30

```
```{r}
c1 %>%
    group_by(Cult) %>%
    summarise(
        Weight = mean(HeadWt, na.rm = TRUE), 
        sd = sd(HeadWt, na.rm = TRUE),
        n = n()
    )
#> # A tibble: 2 x 4
#>   Cult  Weight    sd     n
#>   <fct>  <dbl> <dbl> <int>
#> 1 c39    2.9   0.822    30
#> 2 c52    2.23  0.828    30

```
```{r}
# 复制数据，并移除所有含有 c52 和 d21 的行
c2 <- filter(cabbages, !( Cult == "c52" & Date == "d21" )) 
c2a <- c2 %>%
  group_by(Cult, Date) %>%
  summarise(Weight = mean(HeadWt))

ggplot(c2a, aes(x = Date, fill = Cult, y = Weight)) +
  geom_col(position = "dodge")

```
```{r}
library(tidyr)
c2b <- c2a %>% 
    ungroup() %>% 
    complete(Cult, Date)

ggplot(c2b, aes(x = Date, fill = Cult, y = Weight)) +
    geom_col(position = "dodge")

# 复制数据，并移除所有含有 c52 和 d21 的行 
c2 <- filter(cabbages, !( Cult == "c52" & Date == "d21" )) 
c2a <- c2 %>%
  group_by(Cult, Date) %>%
  summarise(Weight = mean(HeadWt))

ggplot(c2a, aes(x = Date, fill = Cult, y = Weight)) +
    geom_col(position = "dodge")

library(tidyr)
c2b <- c2a %>%
    ungroup() %>%
    complete(Cult, Date)

ggplot(c2b, aes(x = Date, fill = Cult, y = Weight)) +
    geom_col(position = "dodge")

```

## 15.18 使用标准误差和置信区间来汇总数据
```{r}
library(MASS) # 加载 MASS 是为了使用 cabbages 数据集
library(dplyr)

ca <- cabbages %>% 
  group_by(Cult, Date) %>%
  summarise(
    Weight = mean(HeadWt), 
    sd = sd(HeadWt),
    n = n(),
    e = sd / sqrt(n)
)

#> # A tibble: 6 x 6
#> # Groups:    Cult [?]
#>   Cult   Date Weight    sd       n      se
#>   <fct> <fct>  <dbl> <dbl> <int> <dbl>
#> 1 c39     d16   3.18 0.957    10 0.303
#> 2 c39     d20   2.8  0.279    10 0.0882
#> 3 c39     d21   2.74 0.983    10 0.311
#> 4 c52     d16   2.26 0.445    10 0.141
#> 5 c52     d20   3.11 0.791    10 0.250
#> 6 c52     d21   1.47 0.211    10 0.0667

```
```{r}
ciMult <- qt(.975, ca$n-1) 
ciMult
#> [1] 2.262157 2.262157 2.262157 2.262157 2.262157 2.262157

```
```{r}
ca$ci <- ca$se * ciMult
ca
#> # A tibble: 6 x 7
#> # Groups:    Cult [?]
#>   Cult  Date Weight    sd       n       se  ci95
#>  <fct> <fct>  <dbl> <dbl> <int>  <dbl> <dbl>
#> 1 c39    d16   3.18 0.957    10 0.303  0.684
#> 2 c39    d20   2.8 0.279     10 0.0882 0.200
#> 3 c39    d21   2.74 0.983    10 0.311  0.703
#> 4 c52    d16   2.26 0.445    10 0.141  0.318
#> 5 c52    d20   3.11 0.791    10 0.250  0.566
#> 6 c52    d21   1.47 0.211    10 0.0667 0.151

```
```{r}
ca$ci95 <- ca$se * qt(.975, ca$n)

```
```{r}
summarySE <- function(data = NULL, measurevar, groupvars = NULL, na.rm = FALSE, 
                      conf.interval = .95, .drop = TRUE) {

    # 新版本的 length 可以处理缺失值 : 如果 na.rm==T，则排除缺失值
    length2 <- function (x, na.rm=FALSE) {
        if (na.rm) sum(!is.na(x))
        else    length(x)
    }
    groupvars <- rlang::syms(groupvars)
    measurevar <- rlang::sym(measurevar)

    datac <- data %>%
        dplyr::group_by(!!!groupvars) %>%
        dplyr::summarise(
            N = length2(!!measurevar, na.rm = na.rm), 
            sd = sd (!!measurevar, na.rm = na.rm), 
            !!measurevar:=mean (!!measurevar,na.rm=na.rm), 
            se = sd / sqrt(N),
            # 计算标准差的置信空间乘子
            # 为置信空间计算 t 统计量
            # 比如说，如果 conf.interval 是 .95, 使用 .985(上/下)，计算公式是 df=N-1 ci = se * qt(conf.interval/2 + .5, N - 1)
        ) %>%
        dplyr::ungroup() %>%
        # Rearrange the columns so that sd, se, ci are last 
        dplyr::select(seq_len(ncol(.) - 4), ncol(.) - 2, sd, se, ci)
    
    datac
}

```
```{r}
# 移除 c52 和 d21 对应的所有行
c2 <- filter(cabbages, !(Cult == "c52" & Date == "d21" ))

# 将一些值设置为 NA
c2$HeadWt[c(1, 20, 45)] <- NA
summarySE(c2, "HeadWt", c("Cult", "Date"),
conf.interval = .99, na.rm = TRUE, .drop = FALSE)
#> # A tibble: 5 x 7
#>  Cult   Date     N HeadWt      sd      se       ci
#>  <fct> <fct> <int>  <dbl> <dbl> <dbl>  <dbl>
#> 1 c39    d16     9  3.26  0.982 0.327  1.10
#> 2 c39    d20     9  2.72  0.139 0.0465 0.156
#> 3 c39    d21    10  2.74  0.983 0.311  1.01
#> 4 c52    d16    10  2.26  0.445 0.141  0.458
#> 5 c52    d20     9  3.04  0.809 0.270  0.905

```

## 15.19 把数据框从“宽”变“长”
```{r}
library(gcookbook) # 加载 gcookbook 是为了使用 anthoming 数据集
anthoming
#>  angle expt ctrl
#> 1 -20     1    0
#> 2 -10     7    3
#> 3   0     2    3
#> 4  10     0    3
#> 5  20     0    1

```
```{r}
library(tidyr)
gather(anthoming, condition, count, expt, ctrl)
#>   angle condition count
#> 1  -20       expt     1
#> 2  -10       expt     7
#>  ...<6 more rows>...
#> 9  10       ctrl      3
#> 10 20       ctrl      1

```
```{r}
gather(anthoming, condition, count, expt, ctrl)
# 用'-'开头意味着这一列不是值列
gather(anthoming, condition, count, -angle)

```
```{r}
# 源数据
drunk
#>      sex 0-29 30-39 40-49 50-59 60+
#> 1   male  185     207     260     180  71
#> 2 female    4      13      10       7  10

# 尝试只对 0-29 和 30-39 gather()
drunk %>%
    gather(age, count, "0-29", "30-39")
#>      sex 40-49 50-59 60+   age count
#> 1   male   260     180  71 0-29    185
#> 2 female    10     7  10 0-29      4
#> 3   male   260   180  71 30-39   207
#> 4 female    10     7  10 30-39    13

```
```{r}
library(dplyr)  # 为使用 select() 函数

drunk %>%
    select(sex, "0-29", "30-39") %>%
    gather(age, count, "0-29", "30-39")
#>      sex   age count
#> 1     male  0-29   185
#> 2 female  0-29       4
#> 3     male 30-39   207
#> 4 female 30-39      13

```
```{r}
plum_wide
#>  length      time dead alive
#> 1    long     at_once     84   156
#> 2    long in_spring  156    84
#> 3 short   at_once  133     107
#> 4 short in_spring  209      31

# 将 length 和 time 用作标识变量（但不把它们命名为值变量）
gather(plum_wide, "survival", "count", dead, alive)
#>  length      time survival count
#> 1    long     at_once       dead    84
#> 2    long in_spring     dead   156
#>  ...<4 more rows>...
#> 7 short   at_once    alive   107
#> 8 short in_spring    alive    31

```
```{r}
# 复制数据
co <- corneas
# 添加 ID 列
co$id <- 1:nrow(co)

gather(co, "eye", "thickness", affected, notaffected)
#>   id         eye thickness
#> 1    1      affected       488
#> 2    2      affected       478
#>  ...<12 more rows>...
#> 15 7 notaffected       464
#> 16 8 notaffected       476

```

## 15.20 把数据框从“长”变“宽”
```{r}
library(gcookbook) # 加载 gcookbook 是为了使用 plum 数据集
plum
#>   length     time survival count
#> 1    long     at_once       dead    84
#> 2    long in_spring     dead   156
#>  ...<4 more rows>...
#> 7 short   at_once    alive   107
#> 8 short in_spring    alive    31

```
```{r}
library(tidyr)
spread(plum, survival, count)
#>  length      time dead alive
#> 1  long   at_once   84   156
#> 2  long in_spring  156    84
#> 3 short   at_once  133   107
#> 4 short in_spring  209    31

```
```{r}
# 用 length 和 survial 创建新列 length_survival
plum %>%
    unite(length_survival, length, survival)
#>  length_survival      time count
#> 1        long_dead     at_once      84
#> 2        long_dead in_spring   156
#>  ...<4 more rows>...
#> 7    short_alive   at_once   107
#> 8    short_alive in_spring    31

# 在 spread() 中使用 length_survival 作为码
plum %>%
    unite(length_survival, length, survival) %>%
    spread(length_survival, count)
#>         time long_alive long_dead short_alive short_dead
#> 1      at_once          156        84           107        133
#> 2  in_spring         84       156            31        209

```

## 15.21 把时间序列数据对象拆分成时间和数据
```{r}
# 查看 nhtemp 时间序列对象
nhtemp
#> Time Series:
#> Start = 1912
#> End = 1971
#> ...
#> [43] 52.0 52.0 50.9 52.6 50.2 52.6 51.6 51.9 50.5 50.9 51.7 51.4 51.7 50.8
#> [57] 51.9 51.8 51.9 53.0

# 得到每次观测的时间
as.numeric(time(nhtemp))
#> [1] 1912 1913 1914 1915 1916 1917 1918 1919 1920 1921 1922 1923 1924 1925
#> [15] 1926 1927 1928 1929 1930 1931 1932 1933 1934 1935 1936 1937 1938 1939
#> [29] 1940 1941 1942 1943 1944 1945 1946 1947 1948 1949 1950 1951 1952 1953
#> [43] 1954 1955 1956 1957 1958 1959 1960 1961 1962 1963 1964 1965 1966 1967
#> [57] 1968 1969 1970 1971

# 得到每次观测的值
as.numeric(nhtemp)
#> [1] 49.9 52.3 49.4 51.1 49.4 47.9 49.8 50.9 49.3 51.9 50.8 49.6 49.3 50.6
#> [15] 48.4 50.7 50.9 50.6 51.5 52.8 51.8 51.1 49.8 50.2 50.4 51.6 51.8 50.9
#> [29] 48.8 51.7 51.0 50.6 51.7 51.5 52.1 51.3 51.0 54.0 51.4 52.7 53.1 54.6
#> [43] 52.0 52.0 50.9 52.6 50.2 52.6 51.6 51.9 50.5 50.9 51.7 51.4 51.7 50.8
#> [57] 51.9 51.8 51.9 53.0

# 把它们放进一个数据框中
nht <- data.frame(year=as.numeric(time(nhtemp)), temp=as.numeric(nhtemp)) 
nht
#>  year temp
#> 1 1912 49.9
#> 2 1913 52.3
#> ...<56 more rows>...
#> 59 1970 51.9
#> 60 1971 53.0

```
```{r}
presidents
#>      Qtr1 Qtr2 Qtr3 Qtr4
#> 1945   NA   87   82   75
#> 1946   63   50   43   32
#> ...
#> 1973   68   44   40   27
#> 1974   28   25   24   24

```
```{r}
pres_rating <- data.frame(
    year = as.numeric(time(presidents)), 
    rating = as.numeric(presidents)
)
pres_rating
#>  year rating
#> 1    1945.00 NA
#> 2    1945.25 87
#>  ...<116 more rows>...
#> 119 1974.50  24
#> 120 1974.75  24

```
```{r}
pres_rating2 <- data.frame(
    year = as.numeric(floor(time(presidents))), 
    quarter = as.numeric(cycle(presidents)), 
    rating = as.numeric(presidents)
)
pres_rating2
#>      year quarter rating
#> 1    1945       1     NA
#> 2    1945       2     87
#>  ...<116 more rows>...
#> 119  1974       3     24
#> 120  1974       4     24

```

