# Chapter 7 注解

## 7.1 添加文本注解
```{r}
p <- ggplot(faithful, aes(x = eruptions, y = waiting)) +
    geom_point()

p +
    annotate("text", x = 3, y = 48, label = "Group 1") +
    annotate("text", x = 4.5, y = 66, label = "Group 2")

```
```{r}
p +
    annotate("text", x = 3, y = 48, label = "Group 1",
            family = "serif", fontface = "italic", colour = "darkred", size = 3) +
    annotate("text", x = 4.5, y = 66, label = "Group 2",
            family = "serif", fontface = "italic", colour = "darkred", size = 3)

```
```{r}
p +
    # 正常情况
    annotate("text", x = 3, y = 48, label = "Group 1", alpha = .1) +
    # 遮盖绘制
    geom_text(x = 4.5, y = 66, label = "Group 2", alpha = .1)

```
```{r}
p +
    annotate("text", x = -Inf, y = Inf, label = "Upper left", hjust = -.2,
            vjust = 2) +
    annotate("text", x = mean(range(faithful$eruptions)), y = -Inf, vjust = -0.4,
            label = "Bottom middle")

```

## 7.2 在注解中使用数学表达式
```{r}
# 一条正态曲线
p <- ggplot(data.frame(x = c(-3,3)), aes(x = x)) +
    stat_function(fun = dnorm)

p +
    annotate("text", x = 2, y = 0.3, parse = TRUE,
            label = "frac(1, sqrt(2 * pi)) * e ^ {-x^2 / 2}")

```
```{r}
p +
    annotate("text", x = 0, y = 0.05, parse = TRUE, size = 4,
            label = "'Function: ' * y==frac(1, sqrt(2*pi)) * e^{-x^2/2}")

```

## 7.3 添加直线
```{r}
library(gcookbook) # 加载 gcookbook 是为了使用 heightweight 数据集

hw_plot <- ggplot(heightweight, aes(x = ageYear, y = heightIn, colour = sex)) +
    geom_point()
    
# 添加横线和竖线
hw_plot +
    geom_hline(yintercept = 60) +
    geom_vline(xintercept = 14)

# 添加有角度的直线
hw_plot +
    geom_abline(intercept = 37.4, slope = 1.75)

```
```{r}
library(dplyr)

hw_means <- heightweight %>%
    group_by(sex) %>%
    summarise(heightIn = mean(heightIn))
    
hw_means
#> # A tibble: 2 x
#>   sex   heightIn
#>   <fct>    <dbl>
#> 1 f         60.5
#> 2 m         62.1

hw_plot +
    geom_hline(
        data = hw_means,
        aes(yintercept = heightIn, colour = sex),
        linetype = "dashed",
        size = 1
    )

```
```{r}
pg_plot <- ggplot(PlantGrowth, aes(x = group, y = weight)) +
    geom_point()
    
pg_plot +
    geom_vline(xintercept = 2)
    
pg_plot +
    geom_vline(xintercept = which(levels(PlantGrowth$group) == "ctrl"))

```

## 7.4 添加线段和箭头
```{r}
library(gcookbook) # 加载 gcookbook 是为了使用 climate 数据集

p <- ggplot(filter(climate, Source == "Berkeley"),
            aes(x = Year, y = Anomaly10y)) +
        geom_line()

p +
    annotate("segment", x = 1950, xend = 1980, y = -.25, yend = -.25)

```
```{r}
library(grid)

p +
    annotate("segment", x = 1850, xend = 1820, y = -.8, yend = -.95,
            colour = "blue", size = 2, arrow = arrow()) +
    annotate("segment", x = 1950, xend = 1980, y = -.25, yend = -.25,
            arrow = arrow(ends = "both", angle = 90, length = unit(.2,"cm")))

```

## 7.5 添加矩形阴影
```{r}
library(gcookbook)  # 加载 gcookbook 是为了使用 climate 数据集

p <- ggplot(filter(climate, Source == "Berkeley"),
            aes(x = Year, y = Anomaly10y)) +
    geom_line()
    
p +
    annotate("rect", xmin = 1950, xmax = 1980, ymin = -1, ymax = 1,
            alpha = .1,fill = "blue")

```

## 7.6 高亮某一元素
```{r}
library(dplyr)

pg_mod <- PlantGrowth %>%
    mutate(hl = recode(group, "ctrl" = "no", "trt1" = "no", "trt2" = "yes"))

```
```{r}
ggplot(pg_mod, aes(x = group, y = weight, fill = hl)) +
    geom_boxplot() +
    scale_fill_manual(values = c("grey85", "#FFDDCC"), guide = FALSE)

```
```{r}
ggplot(PlantGrowth, aes(x = group, y = weight, fill = group)) +
    geom_boxplot() +
    scale_fill_manual(values = c("grey85", "grey85", "#FFDDCC"), guide = FALSE)

```

## 7.7 添加误差线
```{r}
library(gcookbook) # 加载 gcookbook 是为了使用 cabbage_exp 数据集
library(dplyr)

# 为本例抽取 cabbage_exp 数据的一个子集
ce_mod <- cabbage_exp %>%
    filter(Cultivar == "c39")

# 为条形图添加误差线
ggplot(ce_mod, aes(x = Date, y = Weight)) +
    geom_col(fill = "white", colour = "black") +
    geom_errorbar(aes(ymin = Weight - se, ymax = Weight + se), width = .2)

# 为折线图添加误差线
ggplot(ce_mod, aes(x = Date, y = Weight)) +
    geom_line(aes(group = 1)) +
    geom_point(size = 4) +
    geom_errorbar(aes(ymin = Weight - se, ymax = Weight + se), width = .2)

```
```{r}
ce_mod
#>   Cultivar Date Weight        sd  n         se
#> 1      c39  d16   3.18 0.9566144 10 0.30250803
#> 2      c39  d20   2.80 0.2788867 10 0.08819171
#> 3      c39  d21   2.74 0.9834181 10 0.31098410

```
```{r}
cabbage_exp
#>   Cultivar Date Weight        sd  n         se
#> 1      c39  d16   3.18 0.9566144 10 0.30250803
#> 2      c39  d20   2.80 0.2788867 10 0.08819171
#> 3      c39  d21   2.74 0.9834181 10 0.31098410
#> 4      c52  d16   2.26 0.4452215 10 0.14079141
#> 5      c52  d20   3.11 0.7908505 10 0.25008887
#> 6      c52  d21   1.47 0.2110819 10 0.06674995

```
```{r}
# 反例 : 未指定并列宽度
ggplot(cabbage_exp, aes(x = Date, y = Weight, fill = Cultivar)) +
    geom_col(position = "dodge") +
    geom_errorbar(aes(ymin = Weight - se, ymax = Weight + se),
                position = "dodge", width = .2)

# 正例 : 设定并列宽度与条形的相同 (0.9)
ggplot(cabbage_exp, aes(x = Date, y = Weight, fill = Cultivar)) +
    geom_col(position = "dodge") +
    geom_errorbar(aes(ymin = Weight - se, ymax = Weight + se),
                position = position_dodge(0.9), width = .2)

```
```{r}
pd <- position_dodge(.3) # 保存并列参数 , 因为我们要重复使用它

ggplot(cabbage_exp,
        aes(x = Date, y = Weight, colour = Cultivar, group = Cultivar)) +
    geom_errorbar(
        aes(ymin = Weight - se, ymax = Weight + se),
        width = .2,
        size = 0.25,
        colour = "black",
        position = pd
    ) +
    geom_line(position = pd) +
    geom_point(position = pd, size = 2.5)

# 使用 size=0.25 绘制更细的误差线线条 , 使用 size=2.5 绘制更大的点

```

## 7.8 向独立分面添加注解
```{r}
# 创建基本图形
mpg_plot <- ggplot(mpg, aes(x = displ, y = hwy)) +
    geom_point() +
    facet_grid(. ~ drv)

# 存有每个分面所需标签的数据框
f_labels <- data.frame(drv = c("4", "f", "r"), label = c("4wd", "Front", "Rear"))

mpg_plot +
    geom_text(x = 6, y = 40, aes(label = label), data = f_labels)

# 如果你使用 annotate(), 标签将在所有分面上出现
mpg_plot +
    annotate("text", x = 6, y = 42, label = "label text")

```
```{r}
# 此函数返回一个数据框 , 其中的字符串
# 表示回归公式和 R^2 值
# 这些字符串将被认为是 R 中的数学表达式
lm_labels <- function(dat) {
    mod <- lm(hwy ~ displ, data = dat)
    formula <- sprintf("italic(y) == %.2f %+.2f * italic(x)",
                    round(coef(mod)[1], 2), round(coef(mod)[2], 2))
    r <- cor(dat$displ, dat$hwy)
    r2 <- sprintf("italic(R^2) == %.2f", r^2)
    data.frame(formula = formula, r2 = r2, stringsAsFactors = FALSE)
}

library(dplyr)

labels <- mpg %>%
    group_by(drv) %>%
    do(lm_labels(.))

labels
#> # A tibble: 3 x 3
#> # Groups: drv [3]
#>   drv   formula                              r2
#>   <chr> <chr> <chr>
#> 1 4     italic(y) == 30.68 -2.88 * italic(x) italic(R^2) == 0.65
#> 2 f     italic(y) == 37.38 -3.60 * italic(x) italic(R^2) == 0.36
#> 3 r     italic(y) == 25.78 -0.92 * italic(x) italic(R^2) == 0.04

# 绘制公式和 R^2 值
mpg_plot +
    geom_smooth(method = lm, se = FALSE) +
    geom_text(data = labels, aes(label = formula), x = 3, y = 40, parse = TRUE,
            hjust = 0) +
    geom_text(x = 3, y = 35, aes(label = r2), data = labels, parse = TRUE,
            hjust = 0)

```
```{r}
# 计算每组的 R^2 
labels <- mpg %>%
    group_by(drv) %>%
    summarise(r2 = cor(displ, hwy)^2)

labels$r2 <- sprintf("italic(R^2) == %.2f", labels$r2)
labels
#> # A tibble: 3 x 2
#>   drv   r2
#>   <chr> <chr>
#> 1 4     italic(R^2) == 0.65
#> 2 f     italic(R^2) == 0.36
#> 3 r     italic(R^2) == 0.04

```

