# Chapter 6 描述数据分布

## 6.1 绘制简单直方图
```{r}
ggplot(faithful, aes(x = waiting)) +
  geom_histogram()

```
```{r}
faithful
#>   eruptions waiting
#> 1     3.600      79
#> 2     1.800      54
#> 3     3.333      74
#>  ...<266 more rows>...
#> 270   4.417      90
#> 271   1.817      46
#> 272   4.467      74

```
```{r}
# 将变量值保存为一个基本向量
w <- faithful$waiting

ggplot(NULL, aes(x = w)) +
  geom_histogram()

```
```{r}
# 设定组距为5 (每个条形跨5个单位)
ggplot(faithful, aes(x = waiting)) +
  geom_histogram(binwidth = 5, fill = "white", colour = "black")

# 将x的取值切分为15组
binsize <- diff(range(faithful$waiting))/15

ggplot(faithful, aes(x = waiting)) +
  geom_histogram(binwidth = binsize, fill = "white", colour = "black")

```
```{r}
# 保存基本绘图结果
faithful_p <- ggplot(faithful, aes(x = waiting)) 

faithful_p +
  geom_histogram(binwidth = 8, fill = "white", colour="black", origin=31) 

faithful_p +
  geom_histogram(binwidth = 8, fill = "white", colour="black", origin=35)

```

## 6.2 基于分组数据绘制多组直方图
```{r}
library(MASS) # 加载 MASS 是为了使用 birthwt 数据集

# 使用 smoke 作为分面变量
ggplot(birthwt, aes(x = bwt)) + 
  geom_histogram(fill = "white",colour="black") + 
  facet_grid(smoke ~ .)

```
```{r}
birthwt
#>    low age lwt race smoke ptl ht ui ftv  bwt
#> 85   0  19 182    2     0   0  0  1   0 2523
#> 86   0  33 155    3     0   0  0  0   3 2551
#> 87   0  20 105    1     1   0  0  0   1 2557
#>  ...<183 more rows>...
#> 82   1  23  94    3     1   0  0  0   0 2495
#> 83   1  17 142    2     0   0  1  0   0 2495
#> 84   1  21 130    1     1   0  1  0   3 2495

```
```{r}
library(dplyr) 
birthwt_mod <- birthwt
# 将 smoke 转化为因子并赋予新名字
birthwt_mod$smoke <- recode_factor(birthwt_mod$smoke,
                                   '0' = 'No Smoke',
                                   '1' = 'Smoke') 

```
```{r}
ggplot(birthwt_mod, aes(x = bwt)) +
  geom_histogram(fill = "white", colour = "black") +
  facet_grid(smoke ~ .)

```
```{r}
ggplot(birthwt, aes(x = bwt)) +
  geom_histogram(fill = "white", colour = "black") +
  facet_grid(race ~ .)

```
```{r}
ggplot(birthwt, aes(x = bwt)) +
  geom_histogram(fill = "white", colour = "black") +
  facet_grid(race ~ ., scales = "free")

```
```{r}
# 把 smoke 映射给 fill，取消条形堆叠，并使图形半透明
ggplot(birthwt_mod, aes(x = bwt, fill = smoke)) +
  geom_histogram(position = "identity", alpha = .4)

```

## 6.3 绘制密度曲线
```{r}
ggplot(faithful, aes(x = waiting)) +
  geom_density()

```
```{r}
# 使用 expand_limits() 函数扩大 y 轴范围以包含 0 点
ggplot(faithful, aes(x = waiting)) +
  geom_line(stat = "density") +
  expand_limits(y = 0)

```
```{r}
faithful
#>   eruptions waiting
#> 1     3.600      79
#> 2     1.800      54
#> 3     3.333      74
#>  ...<266 more rows>...
#> 270   4.417      90
#> 271   1.817      46
#> 272   4.467      74

```
```{r}
# 将变量值保存在一个简单向量中
w <- faithful$waiting

ggplot(NULL, aes(x = w)) +
  geom_density()

```
```{r}
ggplot(faithful, aes(x = waiting)) +
  geom_line(stat = "density") +
  geom_line(stat = "density", adjust  =.25, colour = "red") +
  geom_line(stat = "density", adjust = 2, colour = "blue")

```
```{r}
ggplot(faithful, aes(x = waiting)) +
  geom_density(fill = "blue", alpha = .2) +
  xlim(35, 105)

# 这段代码将使用 geom_density() 函数绘制一个蓝色多边形，并在顶端添加一条实线
ggplot(faithful, aes(x = waiting)) +
  geom_density(fill = "blue", colour = NA, alpha = .2) +
  geom_line(stat = "density") +
  xlim(35, 105) +
  geom_line(stat = "density")

```
```{r}
ggplot(faithful, aes(x = waiting, y = ..density..)) +
  geom_histogram(fill = "cornsilk", colour = "grey60", size = .2) +
  geom_density() +
  xlim(35, 105)

```

## 6.4 基于分组数据绘制多组密度曲线
```{r}
library(MASS) # 加载 MASS 是为了使用 birthwt 数据集
birthwt_mod <- birthwt %>%
  mutate(smoke = as.factor(smoke))  # 把变量 smoke 转化为因子

# 把变量 smoke 映射给 colour
ggplot(birthwt_mod, aes(x = bwt, colour = smoke)) +
  geom_density()
# 把变量 smoke 映射给 fill，设置 alpha 使填充色半透明
ggplot(birthwt_mod, aes(x = bwt, fill = smoke)) +
  geom_density(alpha = .3)

```
```{r}
birthwt
#>    low age lwt race smoke ptl ht ui ftv  bwt
#> 85   0  19 182    2     0   0  0  1   0 2523
#> 86   0  33 155    3     0   0  0  0   3 2551
#> 87   0  20 105    1     1   0  0  0   1 2557
#>  ...<183 more rows>...
#> 82   1  23 94    3      1   0  0  0   0 2495
#> 83   1  17 142   2      0   0  1  0   0 2495
#> 84   1  21 130   1      1   0  1  0   3 2495

```
```{r}
ggplot(birthwt_mod, aes(x = bwt)) +
  geom_density() +
  facet_grid(smoke ~ .)

```
```{r}
levels(birthwt_mod$smoke)
#> [1] "0" "1"

birthwt_mod$smoke <- recode(birthwt_mod$smoke, '0' = 'No Smoke', '1' = 'Smoke')

```
```{r}
ggplot(birthwt_mod, aes(x = bwt)) +
  geom_density() +
  facet_grid(smoke~.)

```
```{r}
ggplot(birthwt_mod, aes(x = bwt, y = ..density..)) +
  geom_histogram(binwidth = 200, fill = "cornsilk", colour = "grey60", size = .2) +
  geom_density() +
  facet_grid(smoke ~ .)

```

## 6.5 绘制频数分布折线图
```{r}
ggplot(faithful, aes(x = waiting)) +
  geom_freqpoly()

```
```{r}
ggplot(faithful, aes(x = waiting)) +
  geom_freqpoly(binwidth = 4)

```
```{r}
# 将组数设定为 15
binsize <- diff(range(faithful$waiting))/15

ggplot(faithful, aes(x = waiting)) + 
  geom_freqpoly(binwidth = binsize)

```

## 6.6 绘制基本箱型图
```{r}
library(MASS) # # 加载 MASS 是为了使用 birthwt 数据集

# 使用 factor() 函数将数值型变量转化为离散型
ggplot(birthwt, aes(x = factor(race), y = bwt)) +
  geom_boxplot()

```
```{r}
birthwt
#>    low age lwt race smoke ptl ht ui ftv  bwt
#> 85   0  19 182    2     0   0  0  1   0 2523
#> 86   0  33 155    3     0   0  0  0   3 2551
#> 87   0  20 105    1     1   0  0  0   1 2557
#>  ...<183 more rows>...
#> 82   1  23 94    3      1   0  0  0   0 2495
#> 83   1  17 142   2      0   0  1  0   0 2495
#> 84   1  21 130   1      1   0  1  0   3 2495

```
```{r}
ggplot(birthwt, aes(x = factor(race), y = bwt)) + 
  geom_boxplot(width = .5)

```
```{r}
ggplot(birthwt, aes(x = factor(race), y = bwt)) + geom_boxplot(outlier.size = 1.5, outlier.shape = 21)

```
```{r}
ggplot(birthwt, aes(x = 1, y = bwt)) + 
  geom_boxplot() + 
  scale_x_continuous(breaks = NULL) + 
  theme(axis.title.x = element_blank())

```

## 6.7 向箱形图添加槽口
```{r}
library(MASS) # 加载 MASS 是为了使用 birthwt 数据集
ggplot(birthwt, aes(x = factor(race), y = bwt)) + 
  geom_boxplot(notch = TRUE)

```

## 6.8 向箱形图添加均值
```{r}
library(MASS) # 加载 MASS 是为了使用 birthwt 数据集
ggplot(birthwt, aes(x = factor(race), y = bwt)) + 
  geom_boxplot() + 
  stat_summary(fun.y = "mean", geom = "point", shape = 23, size = 3, 
               fill = "white")

```

## 6.9 向箱形图添加均值
```{r}
library(gcookbook) # 加载 gcookbook 是为了使用 heightweight 数据集

# 使用 heightweight 数据集创建一个基本绘图
hw_p <-ggplot(heightweight, aes(x = sex, y = heightIn)) 

hw_p + 
  geom_violin()

```
```{r}
hw_p +
  geom_violin() +
  geom_boxplot(width = .1, fill = "black", outlier.colour = NA) +
  stat_summary(fun.y = median, geom = "point", fill = "white", shape = 21, size = 2.5)

```
```{r}
hw_p +
  geom_violin(trim = FALSE) 

```
```{r}
# 根据观测值的数目成正比例缩放面积
hw_p + 
  geom_violin(scale = "count")

```
```{r}
# 更平滑
hw_p + 
  geom_violin(adjust = 2)

# 欠平滑
hw_p + 
  geom_violin(adjust = .5)

```

## 6.10 绘制点图
```{r}
library(gcookbook) # 加载 gcookbook 是为了使用 countries 数据集
library(dplyr)

# 保存调整后的数据集，它仅包括人均消费大于 2000 USD 的国家在 2009 年的数据
c2009 <- countries %>% 
  filter(Year==2009 & healthexp>2000)

# 利用 c2009 创建一个基本的 ggplot 对象 c2009_p
c2009_p <- ggplot(c2009, aes(x = infmortality))

c2009_p +
  geom_dotplot()

```
```{r}
c2009_p + 
  geom_dotplot(binwidth = .25) + 
  geom_rug() + 
  scale_y_continuous(breaks = NULL) +   # 移除刻度线
  theme(axis.title.y = element_blank()) # 移除坐标轴标签

```
```{r}
c2009_p +
  geom_dotplot(method = "histodot", binwidth = .25) +
  geom_rug() + 
  scale_y_continuous(breaks = NULL) + 
  theme(axis.title.y = element_blank())

```
```{r}
c2009_p + 
  geom_dotplot(binwidth = .25, stackdir="center") + 
  scale_y_continuous(breaks=NULL) + 
  theme(axis.title.y = element_blank())

c2009_p +
  geom_dotplot(binwidth = .25, stackdir="centerwhole") + 
  scale_y_continuous(breaks=NULL) + 
  theme(axis.title.y = element_blank())
grid.arrange(g1, g2, ncol=2)

```

## 6.11 基于分组数据绘制多个点图
```{r}
library(gcookbook) # 加载 gcookbook 是为了使用 heightweight 数据集

ggplot(heightweight, aes(x = sex, y = heightIn)) +
  geom_dotplot(binaxis = "y", binwidth = .5, stackdir = "center")

```
```{r}
ggplot(heightweight, aes(x = sex, y = heightIn)) + 
  geom_boxplot(outlier.colour = NA, width = .4) +
  geom_dotplot(binaxis = "y", binwidth = .5, stackdir = "center", fill = NA)

```
```{r}
ggplot(heightweight, aes(x = sex, y = heightIn)) +
  geom_boxplot(aes(x = as.numeric(sex) + .2, group = sex), width = .25) +
  geom_dotplot(
    aes(x = as.numeric(sex) - .2, group = sex), 
    binaxis = "y", binwidth = .5, 
    stackdir = "center"
  ) +
  scale_x_continuous(
    breaks = 1:nlevels(heightweight$sex), 
    labels = levels(heightweight$sex)
  )

```

## 6.12 绘制二维数据的密度图
```{r}
# 保存一个基础图
faithful_p <- ggplot(faithful, aes(x = eruptions, y = waiting))

faithful_p + 
  geom_point() + 
  stat_density2d()

```
```{r}
# 将 height 映射到颜色的等高线
faithful_p +
  stat_density2d(aes(colour = ..level..))

```
```{r}
# 将密度估计映射给填充色
faithful_p +
  stat_density2d(aes(fill = ..density..), geom = "raster", contour = FALSE)

# 带数据点，并将密度估计映射给 alpha 的瓦片图
faithful_p +
  geom_point() +
  stat_density2d(aes(alpha = ..density..), geom = "tile", contour = FALSE)

```
```{r}
faithful_p +
  stat_density2d(
    aes(fill = ..density..), 
    geom = "raster",
    contour = FALSE, 
    h = c(.5, 5)
)

```

